#!/bin/sh

BASE_PATH=$(cd $(dirname $0); pwd)
SRC_PATH=$BASE_PATH/src

usage()
{
	echo "Usage: $0 [src-path ...]"
}

build()
{
	if [ ! -d $1 ]; then
		echo "$1 not exist!"
		return 1
	fi
	cd $1
	echo "$1 start bullding..."
	make clean
	make
	echo "$1 build completely"
}

if [ $# == 0 ]; then
	ALL_PATH=$(find $SRC_PATH -maxdepth 1 -type d -name "lc*")
	for path in $ALL_PATH; do
		build $path
	done
else
	for path in $@; do
		absolute_path=$SRC_PATH/$path
		build $absolute_path
	done
fi
