#!/bin/sh

BASE_PATH=$(cd $(dirname $0); pwd)
SRC_PATH=$BASE_PATH/src

usage()
{
	echo "Usage: $0 [project-path]..."
}

config()
{
	if [ ! -d $1 ]; then
		echo "$1 does not exist!"
		usage
		exit 1
	fi
	cd $1
	ln -snf $BASE_PATH/header/lc.h
	ln -snf $BASE_PATH/MakefileTempl Makefile
}

build()
{
	if [ ! -d $1 ]; then
		echo "$1 does not exist!"
		usage
		exit 1
	fi
	cd $1
	make clean
	make
}

if [ $# == 0 ]; then
	ALL_PATH=$(find $SRC_PATH -maxdepth 1 -type d -name "lc*")
	for path in $ALL_PATH; do
		config $path
		build $path
	done
else
	for path in $@; do
		absolute_path=$SRC_PATH/$path
		config $absolute_path
		build $absolute_path
	done
fi
